[package]
name = "ldk-gossip-sync"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.11", features = ["derive"] }
anyhow = "1.0.80"
serde = "1"
serde_json = "1"
ldk-node = { git = "https://github.com/lightningdevkit/ldk-node.git" }
log = "*"
